### ISSUE TITLE
Crash pickling a discriminated union in release build

### ISSUE THREAD

**Issue by jmazar** [mbraceproject/FsPickler#102]
I currently have a discriminated union that pickles without any hiccups in debug mode using a BinarySerializer but when I build in release my program crashes when I go to pickle it.

My types look like
  ```
  type BBO = {
        Exchange : string;
        Symbol : string;
        BidPrice : decimal;
        BidSize : decimal;
        AskPrice : decimal;
        AskSize : decimal;
    }

    type MarketMessage = 
        | MarketData of BBO
```

And when I run this code in release it crashes. Works fine in debug.
```
    let pickler = FsPickler.CreateBinarySerializer()
    let m = {Exchange = "CME"; Symbol = "GEU8"; BidPrice=101m; BidSize=1m; AskPrice=102m; AskSize=1m}
    let message = MarketData m
    let bytes = pickler.Pickle<MarketMessage> message
```

This is with a .net core f# console project. I have to use version 5.0.0 of your library because I cannot upgrade Fsharp.core past 4.2.0 (or at least I can't find a way) and 5.1.0 requires Fsharp.core 4.3.2.

**Comment by eiriktsarpalis** [comment]
I can't reproduce with the latest version. What is your stacktrace?

**Comment by jmazar** [comment]
Hi @eiriktsarpalis , thanks for your quick response. After a bit more digging I found that it was an issue elsewhere in my code that was causing the crash later on. Sorry for bothering.
