### ISSUE TITLE
[Question] Anything that could be done to avoid "IOException: Stream was too long"?

### ISSUE THREAD

**Issue by cdrnet** [mbraceproject/FsPickler#107]
I started to get an FsPicklerException when trying to serialize a very large object tree, due to an internal IOException indicating that the Stream was too long. Do you know whether there is a chance to influence this, maybe to increase limits when running in a 64bit process? Or do I simply have to split the object tree into smaller pieces?

Thanks,
Christoph

**Comment by cdrnet** [comment]
It seems I could solve this by serializing directly to a FileStream, i.e. instead of `serializer.Pickle` to a byte array and then writing the bytes to a file, I now directly call `serializer.Serialize` and pass in the file stream.

**Comment by eiriktsarpalis** [comment]
`Pickle` and `UnPickle` are just extension methods that use `MemoryStream` serialization under the good. I think you can't use it for anything larger than a handful of gigs.
