### ISSUE TITLE
Binary serialization across OS's

### ISSUE THREAD

**Issue by tboby** [mbraceproject/FsPickler#109]
I've started using FsPickler as a way of storing pre-computed data for my IDE extension. At compile-time I do some work, then bundle the pickled binary with the extension, which it de-serializes at startup. I figured this should be safe as I'm not relying on the binary format being stable across versions as I re-serialize each compile.

This seems to work fine on windows. However I'm having problems on linux, where I'm getting Null reference exceptions.

Before I start trying to do in-depth debugging (difficult as I don't develop on linux) I thought I'd check:
Should a binary serialization created on Windows deserialize find on Linux?

**Comment by eiriktsarpalis** [comment]
No, neither cross-platform serialization nor storage are design goals or supported by this library. Please refer to [this guide](http://mbraceproject.github.io/FsPickler/#Why-FsPickler)

**Comment by tboby** [comment]
Hah, I read the cross-platform bit as something it does support. Sorry about that.

Shame, I can't find anything else that works at all for F#, so I'll probably just have to accept that risk and use it for caching instead.
