### ISSUE TITLE
Serialize and Deserealize anonimus records in Expressions

### ISSUE THREAD

**Issue by Neftedollar** [mbraceproject/FsPickler#113]
Hey!
I'm trying to send expression from one process to another.
Expression is:
```fsharp
<@ fun (s:string) ->
        let rcrd = {| FstStr = s |}
        rcrd.FstStr
        @>
```
And as tree
```
Let (rcrd, NewRecord (<>f__AnonymousType1712465342`1', s),
     PropertyGet (Some (rcrd), FstStr, []))
```
While I trying to deserialize it (another process) I'm getting error
```
MBrace.FsPickler.FsPicklerException: Error deserializing object of type 'Microsoft.FSharp.Quotations.FSharpExpr'. ---> System.IO.FileNotFoundException: Could not load file or assembly ...
```
It's ok. Deserializer trying to find type `<>f__AnonymousType1712465342`1'`
But maybe deserilizer can understand that it is an anonimus type and maybe it can create another one with same structure?

**Comment by Neftedollar** [comment]
For example like tuples:
```fsharp
<@ fun (s:string) ->
        let rcrd = (s,"tsda")
        let (a,b) = rcrd
        a   @>

**Comment by eiriktsarpalis** [comment]
Does it work when deserializing on the same process?

**Comment by Neftedollar** [comment]
@eiriktsarpalis  checking

**Comment by Neftedollar** [comment]
@eiriktsarpalis 
```fsharp
  let ex = <@ fun (s:string) -> 
        let rcrd = {| Fst = s |} 
        
        rcrd.Fst @>
  printfn "ex %A" ex
  
  let bs = FsPickler.CreateBinarySerializer()
  let bts = bs.Pickle ex
  let exp = bs.UnPickle<Quotations.Expr<string -> string>>(bts)
  printfn "exp unpickled: %A" exp
  let f =  exp.Compile()
  let result = f "LALA"
  printfn "result - %s" result
```
produce this:
```
ex Lambda (s,
        Let (rcrd, NewRecord (<>f__AnonymousType1872059638`1', s),
             PropertyGet (Some (rcrd), Fst, [])))
exp unpickled: Lambda (s,
        Let (rcrd, NewRecord (<>f__AnonymousType1872059638`1', s),
             PropertyGet (Some (rcrd), Fst, [])))
result - LALA
```

**Comment by Neftedollar** [comment]
I see 
https://github.com/eiriktsarpalis/TypeShape/commit/cbc42a91cad1226d8acfc2818f3592aacd2e7e34

**Comment by eiriktsarpalis** [comment]
This is expected behaviour. Anonymous records are still nominal types in disguise, each assembly generates its own definitions. So you can't really deserialize an anonymous record without having the related assembly available, much like normal records.

I'm going to close this issue.

**Comment by Neftedollar** [comment]
ok.
