### ISSUE TITLE
Unpickling unstructured data

### ISSUE THREAD

**Issue by Gabology** [mbraceproject/FsPickler#117]
I have some binary data (packet data) that I need to be able to parse. As I don't control the format I understand that I can implement a custom format provider by implementing `IPickleFormatProvider`. However in this case, it seems these interfaces rely on being able to write/read type metadata. 

The data that I'm working on does not have any type metadata, rather the fields are based on their position in the data. 

```
  Offset: 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 	
00000000: 00 00 21 00 57 6F 57 00 00 08 00 96 0E 36 38 78
00000010: 00 6E 69 57 00 53 55 6E 65 E0 01 00 00 AC 11 90
00000020: 01 03 41 44 41                                     
```

For example 0x0 will be a byte, 0x04 will be a char etc etc.

**Comment by eiriktsarpalis** [comment]
This is not a scenario supported by the library, it's really only intended for CLR remoting.
