### ISSUE TITLE
What happens at deserialization-time if the FsPickler version is different?

### ISSUE THREAD

**Issue by brodyberg** [mbraceproject/FsPickler#28]
Let's say I am using FsPickler version 100. I pickle to Json text and the version 100 is written into the pickled output. 

I deserialize with FsPickler version 100. Everything is fine. 

But what happens when I deserialize with FsPickler 200? Will that happen successfully even though serialization was conducted by a different version of FsPickler?

Thanks, 

Brody

**Comment by dsyme** [comment]
Closing this old question
