### ISSUE TITLE
Pickling to Code Quotations for Deserialization in a Different Runtime

### ISSUE THREAD

**Issue by cloudRoutine** [mbraceproject/FsPickler#59]
I'm trying to use FsPickler to send code quotations over a named pipe from a server running inside of FSI to a client running inside of the Unity3d engine.  The client has a quotation evaluator that it uses to execute code against the engine's internal API.  The issue comes from the reflection based loading of the FSharp.Core and mscorlib at different version numbers 

[Here's an example of the different JSON produced](https://gist.github.com/cloudRoutine/70d692b754a808c692af)

There are also some differences in the instance and id numbers, and the FSI version having a third `Item = null` in  a few places, but I'm not sure how relevant those are to block being deserialized effectively.

Is there a way to specify the target runtime and target version of FSharp.Core for serialization? and if not could this be incorporated as a future feature?

**Comment by eiriktsarpalis** [comment]
This is a common issue typically solved with [binding redirects](https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx). Does the Unity engine provide something similar?

**Comment by dsyme** [comment]
Closing this old question/discussion
