### ISSUE TITLE
Error when deserializing object

### ISSUE THREAD

**Issue by carlosesquivelunono** [mbraceproject/FsPickler#70]
Hello,

I'm having errors when deserializing this object (serialization works fine). The message says "Expected picker for type <type> but instead found System.Object). 

This is my base class, the derived classes only add simple auto-properties.

[Serializable]
    public abstract class ConcurrentEntity<T> : IConcurrentEntity<T> where T : new()
    {
        [NonSerialized]
        private static readonly T LockObject = new T();

```
    [NonSerialized]
    private ConcurrentEntity<T> _snapshotObject;

    [JsonIgnore]
    [CustomReplicationBehavior(ReplicationBehavior.Ignore)]
    [IgnoreDataMember]
    public T LockableObject => LockObject;

    internal void TakeSnapshot()
    {
        _snapshotObject = Clone.ObjectGraph(this);
    }

    internal ConcurrentEntity<T> RetrieveSnapshot()
    {
        return _snapshotObject;
    }
}
```

I'm calling `CSPickler.CreateBinarySerializer.UnPickle<T>`

Thanks!

**Comment by dsyme** [comment]
We would need a full simple repro for this.  Will close - it's quite an old issue - @carlosesquivelunono please reopen if you can provide a step-by-step repro, thanks
