### ISSUE TITLE
omitHeader in bson serializer

### ISSUE THREAD

**Issue by vilinski** [mbraceproject/FsPickler#71]
I could make a PR, but it seems difficult
-  in mono the unit tests are broken because of this [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=40568) (already fixed)
- in windows the additional tests for bson without header are broken for me also, perhaps because bson needs always to be a document, but primitives and arrays are not if there is no header document, containing serialized value
- in mono i have some failed performance tests regardless of my changes, dunno if it was already so in the latest git stand

**Comment by eiriktsarpalis** [comment]
Hi, what is the issue exactly? 

Performance tests are not really unit tests, some of them are expected to fail from time to time.

**Comment by vilinski** [comment]
created a test [PR #72 ](https://github.com/nessos/FsPickler/pull/72)

**Comment by eiriktsarpalis** [comment]
BSON is being deprecated by Newtonsoft, so don't think this is relevant anymore.
