### ISSUE TITLE
Deserialisation of JSON null string

### ISSUE THREAD

**Issue by roblenders** [mbraceproject/FsPickler#75]
In using your deserialiser I have found that when deserialising a JSON null value to a "string option" type the value returned is "Some(null)" instead of "None".

**Comment by eiriktsarpalis** [comment]
Could you please provide a detailed reproduction of this issue? In any case, the library has been designed to only work with FsPickler-to-FsPickler serialization roundtrips, deserialization of arbitrary json/xml formats cannot be guaranteed and usually results in exceptions.

**Comment by roblenders** [comment]
Apologies, upon attempting to reproduce the error I found that the problem was further upstream in my processing (the Some(null) value was already created). FsPickler correctly serialised and deserialised my erroneous value.
