### ISSUE TITLE
Documentation out of date with namespaces

### ISSUE THREAD

**Issue by jackmott** [mbraceproject/FsPickler#76]
The documentation (here)[https://nessos.github.io/FsPickler/] and (here)[https://nessos.github.io/FsPickler/tutorial.html]  indicate opening the Nessos.FsPickler namespaces, it appears to be MBrace.FsPickler now.  This appears fixed already in the master repo, looks like it just needs to get pushed up to the website.

**Comment by adicirstei** [comment]
I think you should check the documentation here: http://mbraceproject.github.io/FsPickler/

**Comment by jackmott** [comment]
Aha!
The old one is still the first google search result when you search for FsPickler.

**Comment by eiriktsarpalis** [comment]
The project has been moved, so I'm surprised that the old paged is still being by github. Not sure what is amiss.

**Comment by eiriktsarpalis** [comment]
Contacted github support, they confirmed it was due to a bug on their side.
Old websites have now been removed.
