### ISSUE TITLE
Wrong serialization/deserialization enums which has DataContract attribute applied

### ISSUE THREAD

**Issue by vasily-kirichenko** [mbraceproject/FsPickler#77]
```fsharp
[<DataContract>]
type E =
    | C1 = 1uy
    | C2 = 2uy
    | C3 = 3uy
    | C4 = 4uy

let p = FsPickler.CreateBinarySerializer()
let ms = new MemoryStream()
//let action = TfpAction.Delete
let x = E.C2
p.Serialize(ms, x, leaveOpen = true)
ms.Position <- 0L
let x': E = p.Deserialize ms
// val x' : E = 0
x' = x
// false
```
Removing `DataContract` attribute solves the problem.

**Comment by eiriktsarpalis** [comment]
Interesting. I wasn't aware that DataContract applies to enumerations, which occurs through use of the [`EnumMember`](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.enummemberattribute(v=vs.110).aspx) attribute. DataContract-annotated enums will fail serialization if attempting to write a value that does not specify an `EnumMember` attribute. In other words, "correct behaviour" in the context of your code would result in a serialization exception.

I must say I dislike this design, and it's a good question whether FsPickler should attempt to replicate this behaviour or just ignore the attributes altogether.
