### ISSUE TITLE
Question: How to serialize option type to more idiomatic json?

### ISSUE THREAD

**Issue by 2moveit** [mbraceproject/FsPickler#79]
Hi, if I serialze this:

    open MBrace.FsPickler.Json
    let private jsonSerializer = FsPickler.CreateJsonSerializer(indent = true, omitHeader = true)
    let serialize obj = jsonSerializer.PickleToString(obj)

    type MyType = {Key: string; Value:string option}
    let o1 = {Key="None value test"; Value=None}
    let o2 = {Key="Some Value test"; Value=Some "Text"}

    serialize o1
    serialize o2

The json result is:

    { "Key": "None value test",
      "Value": null }
    { "Key": "Some Value test",
      "Value": { "Some": "Text" }}

Is it somehow possible to change that behavior to always get a result like this in stead of null and a nested value?

    { "Key": "None value test" }
    { "Key": "Some Value test",
      "Value": "Text"}
During my research I found a possible solution on [SO](http://stackoverflow.com/questions/41578734/json-serialization-of-optional-values-with-fspickler) but they are using Json.Net directly.
I think it should be somehow possible to configure FsPickler so that this result is possible.

**Comment by eiriktsarpalis** [comment]
No, managing the shape of the serialization formats is beyond the [design goals](http://mbraceproject.github.io/FsPickler/index.html#Why-FsPickler) of this library. While you could use [pickler combinators](http://mbraceproject.github.io/FsPickler/tutorial.html#Picklers-and-Pickler-combinators) to influence how serialized types look like, this will only take you so far.

**Comment by 2moveit** [comment]
Ahh ok, thanks for clarification and the hint with the combinators. I tried it with combinator but so far I was not able to get it to work. It's not really the serialization format that is important to me. If I try to deserialize it e.g. into a C# class it's not that nice with the "Some" key. So it's more interoperability within .NET from my point of view. So it would be really nice to figure it out how to achieve it with combinators.

**Comment by eiriktsarpalis** [comment]
FsPickler is a serializer for types, so you should always deserialize using the same .NET type.

**Comment by 2moveit** [comment]
OK, thanks
