### ISSUE TITLE
FsPickler.CSharp - Wrong version on NuGet?

### ISSUE THREAD

**Issue by TechInterMezzo** [mbraceproject/FsPickler#96]
I'm not sure, if this is an error, but there is a one month old 4.3.0 version on NuGet. The most recent version seems to be 4.0.1 (only 14 days old).

https://www.nuget.org/packages/FsPickler.CSharp

Its the same for the JSON package.

https://www.nuget.org/packages/FsPickler.Json

**Comment by eiriktsarpalis** [comment]
Thanks. It's a bad release which I forgot to unlist. Thanks for pointing out
