### ISSUE TITLE
Stability of binary serialization across FsPickler versions

### ISSUE THREAD

**Issue by cmeeren** [mbraceproject/FsPickler#98]
I'm considering using FsPickler (and binary serialization using `Pickle`/`UnPickle`? Haven't really looked into it) to share domain objects between a Xamarin mobile app and a server (the types would be defined in an assembly referenced by both the app and the server). However, if the serialization result somehow changes between different versions of FsPickler and there's no option to keep the old behavior, that means I am effectively hindered from ever upgrading FsPickler again since upgrading it in the API would break the communication with all existing mobile app installations.

I'm of course extra worried since you state in the documentation that FsPickler is not a library used with version tolerance in mind.

If the above was understandable: Would you recommend I use another binary serializer than FsPickler for the usage I described?

**Comment by eiriktsarpalis** [comment]
> Would you recommend I use another binary serializer than FsPickler for the usage I described?
Yes.

**Comment by cmeeren** [comment]
Great, thanks. :)
